export type deviceNameType =
  | "button"
  | "buzzer"
  | "dcmotor"
  | "dimmer"
  | "ledicon"
  | "lightsensor"
  | "proximitysensor"
  | "pressuresensor"
  | "servomotor"
  | "slider"
  | "heatsensor"
  | "tilt"
  | "temperaturesensor"
  | "vibrationmotor";
