name: Staging S3 Deployment - AWS
on:
    push:
        branches:
            - beta
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 12

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: NPM Install
              run: |
                  npm install
            - name: Beta Build
              run: |
                  npm run build-client
              env:
                  REACT_APP_FEATURE_FLAG_LESSON_VIEW: false
                  REACT_APP_FEATURE_FLAG_LESSON_BUILDER: true
                  REACT_APP_IFRAME_LINK_LAUNCHER: true
                  REACT_APP_SAMLABS_COGNITO_DOMAIN: ${{ secrets.SAMLABS_COGNITO_DOMAIN }}
                  REACT_APP_SAMLABS_COGNITO_USER_POOL_ID: ${{ secrets.SAMLABS_COGNITO_USER_POOL_ID }}
                  REACT_APP_SAMLABS_COGNITO_CLIENT_ID: ${{ secrets.SAMLABS_COGNITO_CLIENT_ID }}
                  REACT_APP_APPSYNC_ENDPOINT: 'https://m77gx6fdurbwjhf4qdxuglwmmi.appsync-api.us-east-1.amazonaws.com/graphql'
                  REACT_APP_ROSTER_UPLOAD_URL: 'https://vdkru7v829.execute-api.us-east-1.amazonaws.com/beta/roster/uploadToS3'
                  REACT_APP_NEXT_JS_CONTENT_HUB: 'https://develop.studioneo.samlabs.com'
                  REACT_APP_SAMSCRIPT_URL: 'https://samscript-standalone.samlabs.com'
                  REACT_APP_INACTIVITY_SESSION_TIMEOUT: 30
            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_BETA_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  SOURCE_DIR: 'build'
            - name: Invalidate CloudFront
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                  DISTRIBUTION: 'E2PT9LBUTMSHXB'
                  PATHS: '/*'
                  AWS_REGION: 'us-east-1'
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
